GET http://localhost:3000/posts
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiTWFkZHkiLCJpYXQiOjE2NzQ1MDA5NTksImV4cCI6MTY3NDUwMDk3NH0.LjKJgaqptxeboElqGryWsN32otjMvWBzAaje_h0jbus

###

POST http://localhost:4000/token
Content-Type: application/json

{
    "token":"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiTWFkZHkiLCJpYXQiOjE2NzQ1MDA5MzV9.FAYfbqB9KLRDmJ0Cnz4UTnpCwYdJnwrpmd4ldE7pnog"
}

###

POST http://localhost:4000/login
Content-Type: application/json

{
    "username":"Maddy"
}

###
DELETE http://localhost:4000/logout
Content-Type: application/json

{
    "token":"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiTWFkZHkiLCJpYXQiOjE2NzQ1MDA5MzV9.FAYfbqB9KLRDmJ0Cnz4UTnpCwYdJnwrpmd4ldE7pnog"
}

//use this file to send rest requests : install rest client extension in vs code.