GET http://localhost:3000/posts
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiTWFkZHkiLCJpYXQiOjE2NzQ1MDA3NzQsImV4cCI6MTY3NDUwMDc4OX0.hLz56qmuxiGnFakJrVs0bJUAnnCzOCA0DCp5bC9Lh8U

POST http://localhost:4000/token
Content-Type: application/json

{
    "token":"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiTWFkZHkiLCJpYXQiOjE2NzQ1MDA3NDl9.wm3DhGE8rCAELf8S3-ZXqzTtNqMiNyEzQYKvYtGyThk"
}

###

POST http://localhost:4000/login
Content-Type: application/json

{
    "username":"Maddy"
}

###
DELETE http://localhost:4000/logout
Content-Type: application/json

{
    "token":"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiTWFkZHkiLCJpYXQiOjE2NzQ1MDAzMDR9.fBUmsDcr5YuQYswc7WTttiEoVIxKphjOXQ5yupVnnoc"
}

//use this file to send rest requests : install rest client extension in vs code.